//
//  TicketController.h
//  TradeItTicketViewSDK
//
//  Created by Antonio Reyes on 7/2/15.
//  Copyright (c) 2015 Antonio Reyes. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "TradeItStockOrEtfTradeSession.h"

@interface TradeItTicketController : NSObject

/**
 *  Presents the full screen version of the TradeIt Trading Ticket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 */
+(void) showFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view;

/**
 *  Presents the full screen version of the TradeIt Trading Ticket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 *  @param callback     Code block to be executed after we have returned control of the view back to you.
 */
+(void) showFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view onCompletion:(void(^)(void)) callback;


/**
 *  Testing version of showFullTicketWithPublisherApp, the main difference being the inclusion of the Dummy broker
 *
 */
+(void) debugShowFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view;

/**
 *  Testing version of showFullTicketWithPublisherApp, the main difference being the inclusion of the Dummy broker
 *
 */
+(void) debugShowFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view onCompletion:(void(^)(void)) callback;

@end
