//
//  TradeItAuthController.h
//  TradeItIosTicketSDK
//
//  Created by Antonio Reyes on 10/23/15.
//  Copyright © 2015 Antonio Reyes. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "TradeItAuthControllerResult.h"

@interface TradeItAuthController : NSObject

/**
 *  Create your own instance to have more control over defaults/callbacks, after setting all properties call showTicket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 *   *  @param onCompletion callback block once network request is complete, will have authResult passed in indicating if sucessfully validated credentials
 */
+(void) initBrokerLinkWithPublisherApp: (NSString *) publisherApp viewController:(UIViewController *) view onCompletion: (void (^)(TradeItAuthControllerResult *)) completionBlock;

/**
 *  @param brokerIdentifier the broker short name as documented in TradeItEMS Api
 *  @param username the username/acct#/email that the user uses to login to their broker
 *  @param password the password used to login to the broker
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param onCompletion callback block once network request is complete, will have authResult passed in indicating if sucessfully validated credentials
 */
+(void) linkBroker: (NSString *) broker withUsername: (NSString *) username andPassword:(NSString *) password andPublisherApp:(NSString *) publisherApp onCompletion: (void (^)(TradeItAuthControllerResult *)) completionBlock;

/**
 *  @param broker the string representing the broker (retrieved from getLinkedBrokers)
 *  remove the broker credentials from the keychain
 */
+(void) unlinkBroker: (NSString *) broker;

/**
 *  @return NSArray of brokers the user is linked with, it will use the short names as documented in TradeItEMS Api
 *  if you're displaying this to the end user, you should pass the value(s) through getBrokerDisplayString
 */
+(NSArray *) getLinkedBrokers;

/**
 *  @param brokerIdentifier the broker short name as documented in TradeItEMS Api
 *  @return the consumer friendly version of the broker name (i.e. IB -> Interactive Brokers)
 */
+(NSString *) getBrokerDisplayString:(NSString *) brokerIdentifier;

@end
