//
//  TicketController.h
//  TradeItTicketViewSDK
//
//  Created by Antonio Reyes on 7/2/15.
//  Copyright (c) 2015 Antonio Reyes. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "TradeItStockOrEtfTradeSession.h"

@interface TradeItTicketController : NSObject

/**
 *  Presents the full screen version of the TradeIt Trading Ticket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 */
+(void) showFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view;

/**
 *  Presents the full screen version of the TradeIt Trading Ticket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 *  @param callback     Code block to be executed after we have returned control of the view back to you.
 */
+(void) showFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view onCompletion:(void(^)(void)) callback;

/**
 *  Presents the full screen version of the TradeIt Trading Ticket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param orderAction  Order action can be "buy", "sell", "sellShort" or "buyToCover"
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 */
+(void) showFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice orderAction:(NSString *) action viewController:(UIViewController *) view;

/**
 *  Presents the full screen version of the TradeIt Trading Ticket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param orderAction  Order action can be "buy", "sell", "sellShort" or "buyToCover"
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 *  @param callback     Code block to be executed after we have returned control of the view back to you.
 */
+(void) showFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice orderAction:(NSString *) action viewController:(UIViewController *) view onCompletion:(void(^)(void)) callback;

/**
 *  Testing version of showFullTicketWithPublisherApp, the main difference being the inclusion of the Dummy broker
 *
 */
+(void) debugShowFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view;

/**
 *  Testing version of showFullTicketWithPublisherApp, the main difference being the inclusion of the Dummy broker
 *
 */
+(void) debugShowFullTicketWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view onCompletion:(void(^)(void)) callback;




/**
 *  Create your own instance to have more control over defaults/callbacks, after setting all properties call showTicket
 *
 *  @param publisherApp Your unique id generated by TradeIt
 *  @param symbol       The street symbol of the stock or etf to be traded
 *  @param lastPrice    Last price of the security to be traded
 *  @param view         Presenting view, this is the current UIViewController of your app, on completion we dissmiss the ticket and return control back to this view.
 *
 *  @return TradeItTicketController
 */

- (id) initWithPublisherApp: (NSString *) publisherApp symbol:(NSString *) symbol lastPrice:(double) lastPrice viewController:(UIViewController *) view;

/**
 *  The default number of shares to trade
 */
@property int quantity;

/**
 *  The default order action, can only be buy, sell, sellShort or buyToCover
 */
@property (copy) NSString* action;

/**
 *  The default order type, can only be market, limit, stopLimit, or stopMarket
 */
@property (copy) NSString* orderType;

/**
 *  The default order duration. Possible values are day or gtc.
 */
@property (copy) NSString* expiration;

/**
 *  Set this to get access to the Dummy trading brokerage for testing
 */
@property BOOL debugMode;

/**
 *  Completion block called after the ticket has been exited, immediately after returning control to init'd view controller
 */
@property (copy) void (^onCompletion)(void);

/**
 *  Supply a block that given a symbol will return an updated lastPrice to passed in callback
 */
@property (copy) void (^refreshLastPrice)(NSString * symbol, void(^callback)(double lastPrice));

/**
 *  After setting all desired properties, call this method to launch the ticket
 */
-(void) showTicket;


@end






















